### PR TITLE
Fully allocate endless.img padding

### PR DESCRIPTION
**Pull request by wjt**
https://phabricator.endlessm.com/T13309

This also rolls in a fix for using local image files to install; and a fix to `SetPrivilege`.

### CODE REVIEW

**Comment by wjt** [comment]
@raduancuta any chance you can take a look tomorrow? This seems to work in my testing…

**Comment by raduancuta** [comment]
Not sure about the CanUseLocalFile change: isn't dual boot handled by the hasFilesForDualBoot part?

**Comment by raduancuta** [comment]
The rest looks ok to me.

**Comment by wjt** [comment]
I'm not sure about the CanUseLocalFile change either, I'll check it. Selecting local files wasn't possible before this change and was afterwards. But it's worth getting it right.

**Comment by raduancuta** [comment]
Can you check if proper (hardcoded for now) boot.zip file and its signature are found in the same folder as the installer?

**Comment by wjt** [comment]
You're right, that patch isn't needed. I don't know why it wasn't working for me before, though…

**Pull request merged**
