### PR TITLE
Add analytics for systems capable of running accelerated hypervisors

### PR DESCRIPTION
**Pull request by ManMower**
Test for vt-x/amd-v capabilities being accessible to windows, and add
this to our analytics.

This will help us determine if it's a good idea to promote virtual
machines for users that can't dual boot endless.

https://phabricator.endlessm.com/T29168

### CODE REVIEW

**Comment by ManMower** [comment]
This is a very simple change, perhaps too simple - do we need a special event for "user hit an uninstallable case but had VM capabilities" instead/as well to make this truly useful for us?  or can we mine the analytics successfully with only this change?

Also, I have no idea what the coding style is for this.  I  used tabs like rufus does, and like parts of the function I changed do... Input here would be helpful.

**Comment by wjt** [comment]
> This is a very simple change, perhaps too simple - do we need a special event for "user hit an uninstallable case but had VM capabilities" instead/as well to make this truly useful for us? or can we mine the analytics successfully with only this change?

Good question. I would have to check whether we can query for "count of event X followed by event Y". TBH I think just a raw % of users with VM capability enabled would be interesting in and of itself.

> Also, I have no idea what the coding style is for this. I used tabs like rufus does, and like parts of the function I changed do... Input here would be helpful.

There is no consistent style in the Endless code, sorry. :(

**Review by ramcq — COMMENTED** [review]
If we set up a custom variable in analytics, and report this in the same way as we track OS version, BIOS Vs EFI, etc will be able to slice the population by that variable easily. Attributes as events make it harder to correlate actual events. Eg, does everyone who fails with Bitlocker have Virt - that would inform a certain approach.

Also, is it possible to to also check for a virt capable CPU which is firmware disabled, and for hyper V available, which I suppose would preclude installing our own Virt solution.

**Comment by ManMower** [comment]
@wjt the PR should give us a raw % of vm capable users - but I'll look into rob's suggestion of "custom variables" (I don't know what they are yet...) to give us better mining capabilities.

@ramcq I'm not sure yet how to query if hyper-v is enabled. I think we can query the processor for vt-x/smv and if it's present but the previous test fails we're one of: hyper-v enabled, virtualization disabled in bios, or running on windows 7. A fairly nasty list, but can be deconvolved somewhat - leaving no sensible data for windows 7 users.

It looks like virtualbox is capable of running on systems with hyper-v enabled, at a performance cost - it uses hyper-v API somehow. Never tried it, unsure of performance and reliability.

**Comment by ManMower** [comment]
Ok, I've re-done this with a custom dimension.
I've read that on windows 7 machine we can't rely on these tests to work, so on windows 7 we simply spit out "Unknown" for virtualization caps.
On my windows 10 box HyperV is sent when hyperv is *enabled* and holding the rights to vt-x/smv
"None" occurs when smv is disabled in my bios
"Capable" when it's all good.

**Review by wjt — APPROVED** [review]

**Pull request merged**
